<#
.SYNOPSIS
  Builds AegisDesk-Support.exe -- the file you send to someone who needs help.

.DESCRIPTION
  The relay URL and enrollment key are compiled in, so the person receiving it
  double-clicks one file and reads two numbers off the screen. They do not
  install anything, do not need admin rights, and nothing is left on their
  computer when they close the window.

  Build this once. The .exe is what you distribute -- put it on GitHub
  Releases, a shared drive, or your own site.

.PARAMETER Relay
  Your relay URL, e.g. wss://desk.myrestaurant.com or the Tailscale one.

.PARAMETER EnrollKey
  From the relay's Admin page. Compiled in, so treat the .exe as sensitive:
  anyone holding it can offer their screen to your relay. It does NOT let them
  view anyone else's screen -- that needs an operator account.

.PARAMETER Brand
  Heading shown in the window. Default "Remote Support".

.PARAMETER Phone
  Optional contact line shown under the numbers, e.g. "(555) 123-4567".

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File build-support-exe.ps1 `
    -Relay wss://desk.myrestaurant.com -EnrollKey abc123 `
    -Brand "Racquel IT Support" -Phone "(555) 123-4567"

.NOTES
  Also builds AegisDeskAgent.exe (the permanent agent) if you pass -AlsoAgent.
#>
param(
  [Parameter(Mandatory = $true)][string]$Relay,
  [Parameter(Mandatory = $true)][string]$EnrollKey,
  [string]$Brand = "Remote Support",
  [string]$Phone = "",
  [switch]$AlsoAgent,
  [switch]$KeepBaked
)

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $here

function Say($m, $c = "Cyan") { Write-Host "  $m" -ForegroundColor $c }

Write-Host ""
Write-Host "  Building the quick-support executable" -ForegroundColor White
Write-Host "  -------------------------------------" -ForegroundColor DarkGray

# ---- normalise the URL so a pasted https:// still works ----
$r = $Relay.Trim()
if ($r -notmatch '://') { $r = "wss://$r" }
$r = $r -replace '^http://', 'ws://' -replace '^https://', 'wss://'
$r = $r.TrimEnd('/')
if ($r -match '^ws://' -and $r -notmatch '127\.0\.0\.1|localhost') {
  Say "WARNING: ws:// is unencrypted at the transport layer. Use wss:// for anything off this machine." "Yellow"
}
Say "relay: $r"

# ---- bake the configuration in ----
$bakedPath = Join-Path $here "aegis_agent\_baked.py"
$escape = { param($v) $v -replace '\\', '\\\\' -replace '"', '\"' }
@"
# Generated by build-support-exe.ps1 -- do not edit, do not commit.
RELAY_URL = "$(& $escape $r)"
ENROLL_KEY = "$(& $escape $EnrollKey)"
BRAND = "$(& $escape $Brand)"
SUPPORT_PHONE = "$(& $escape $Phone)"
"@ | Set-Content -Path $bakedPath -Encoding UTF8
Say "baked configuration into aegis_agent\_baked.py"

try {
  Say "installing build tooling"
  python -m pip install --upgrade pyinstaller --quiet --disable-pip-version-check
  python -m pip install -r (Join-Path $here "requirements.txt") --quiet --disable-pip-version-check

  $common = @(
    "--onefile", "--windowed", "--clean", "--noconfirm",
    "--collect-all", "mss",
    "--collect-all", "PIL",
    "--hidden-import", "websocket",
    "--hidden-import", "cryptography.hazmat.backends.openssl",
    "--hidden-import", "tkinter",
    "--exclude-module", "matplotlib",
    "--exclude-module", "pytest",
    "--exclude-module", "IPython"
  )

  Say "building AegisDesk-Support.exe (a few minutes)"
  python -m PyInstaller --name "AegisDesk-Support" @common "support-entry.py"
  if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed for the support build" }

  if ($AlsoAgent) {
    Say "building AegisDeskAgent.exe (permanent agent)"
    python -m PyInstaller --name "AegisDeskAgent" @common "--collect-all" "pystray" "agent-entry.py"
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed for the agent build" }
  }
} finally {
  if (-not $KeepBaked -and (Test-Path $bakedPath)) {
    Remove-Item $bakedPath -Force
    Say "removed the baked config from the source tree (the .exe keeps its copy)" "DarkGray"
  }
}

$exe = Join-Path $here "dist\AegisDesk-Support.exe"
Write-Host ""
if (Test-Path $exe) {
  $size = [math]::Round((Get-Item $exe).Length / 1MB, 1)
  Say "Built: dist\AegisDesk-Support.exe  ($size MB)" "Green"
  Write-Host ""
  Say "Send that one file to whoever needs help. They double-click it and read" "DarkGray"
  Say "you the two numbers. Nothing is installed and nothing is left behind." "DarkGray"
  Write-Host ""
  Say "To publish it so people can download it themselves:" "DarkGray"
  Say "  gh release create v1.0 dist\AegisDesk-Support.exe --title `"Remote Support`" --notes `"Double-click to start a support session.`"" "DarkGray"
} else {
  Say "build finished but dist\AegisDesk-Support.exe is missing - check the PyInstaller output" "Red"
  exit 1
}
Write-Host ""
